### PR TITLE
Fix emtpy package on win32

### PR DESCRIPTION
**Pull request by jschueller**
The package was empty on win32
No need for compilers; just install the header

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by marimeireles** [comment]
Woops, I just merged the automatic PR because I thought this was maintained by myself only. Just remember this used to be a mamba dep. is this still true @wolfv ?
Also, is the [PR](https://github.com/conda-forge/exprtk-feedstock/pull/2) I merged defective @jschueller?
Should we rebase yours and merge? Cheers and thanks.

**Comment by jschueller** [comment]
the arm64 PR just merged is fine, I added the migration because I need this for paraview
no problem, I'm rebasing

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
it should be ready to go now

**Comment by marimeireles** [comment]
Cool, thanks!

**Pull request merged**
